# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ed29c29da63c6384483f8dc7135cef64dbdde149d833f060122036d3ca0939d7fc9dec17b646307286cfc31c6044d0b7d4a6c66cc556930b77c1cb847a6edb9

test:
  secret_key_base: 48b78080d8df08527023ff3d4efd51c131f3b9450f01420d7ea85a8d11af5b5aea7701159842b3b493cec1a25e71b5f5d5f42ba5264a4ffedc4dc0c5eab13cdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
